#!/usr/bin/env bash
set -euo pipefail

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    cat <<EOF
Usage: $(basename "$0") [no arguments]
Builds the Firefox extension zip and writes it to dist/.

Firefox ships the SAME background.js/scraper.js/icons as Chrome (the shared
chrome-extension/ source); only the manifest differs and is generated by
scripts/gen-firefox-manifest.py, plus the one-line chrome-compat.js shim.

The zip is UNSIGNED. Firefox stable/ESR only installs an unsigned add-on
TEMPORARILY (about:debugging -> Load Temporary Add-on; removed on restart). For
a permanent install, sign it via AMO (free account + API key):
  web-ext sign --channel=unlisted --source-dir <unzipped build> \\
    --api-key "\$AMO_JWT_ISSUER" --api-secret "\$AMO_JWT_SECRET"
EOF
    exit 0
fi

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSION="$(python3 -c "import json; print(json.load(open('$REPO_DIR/chrome-extension/manifest.json'))['version'])")"
OUT="$REPO_DIR/dist/claude-usage-firefox-${VERSION}.zip"

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

# Stage the shared extension source, minus the Chrome manifest (we generate a
# Firefox one below), tests, and caches. Same exclusions as build-chrome-zip.sh.
rsync -a \
    --exclude 'manifest.json' \
    --exclude 'test/' \
    --exclude '__pycache__/' \
    --exclude '*.pyc' \
    --exclude '.DS_Store' \
    "$REPO_DIR/chrome-extension/" "$STAGE/"

# Generate the Firefox manifest from the Chrome one (single source of truth).
python3 "$REPO_DIR/scripts/gen-firefox-manifest.py" > "$STAGE/manifest.json"

mkdir -p "$REPO_DIR/dist"
rm -f "$OUT"
( cd "$STAGE" && zip -r "$OUT" . -x "*.DS_Store" )
echo "Built: dist/claude-usage-firefox-${VERSION}.zip"
echo ""
echo "Developer load: about:debugging#/runtime/this-firefox -> Load Temporary Add-on -> manifest.json"
echo "                (temporary add-ons are removed when Firefox restarts)"
echo "Permanent:      web-ext sign --channel=unlisted   (needs a free AMO API key)"
