#!/bin/bash
set -e
case "$1" in
    remove|purge)
        update-desktop-database -q /usr/share/applications/ || true
        glib-compile-schemas /usr/share/glib-2.0/schemas/ 2>/dev/null || true
        ;;
esac
